### ISSUE TITLE
Example does not work on OSX with VirtualBox

### ISSUE THREAD

**Issue by MichaelF25** [cloudius-systems/capstan-example-java#2]
Cloned the repository and tried the example as explained without luck.

Output from `capstan run`:

`Created instance: capstan-example-java
OSv v0.16
eth0: 10.0.2.15
This image has an empty command line. Nothing to run.`

Output from `capstan run target/capstan-example-java-1.0-SNAPSHOT-jar-with-dependencies.jar`:
`target/capstan-example-java-1.0-SNAPSHOT-jar-with-dependencies.jar: image format not recognized, unable to run it.`

**Comment by jwaterloo** [comment]
what do windows user do about qemu
...
do you have a windows cross platform tutorial example
...
on windows for both java and C++ getting the following problem
C:\Tutorials\C++\OSv\osv.io\capstan-example-java-master>capstan run
open C:\Users\JWATERLOO\.capstan\repository\C:\Tutorials\C++\OSv\osv.io\capstan-
example-java-master\capstan-example-java-master.vbox: The filename, directory na
me, or volume label syntax is incorrect.

**Comment by dorlaor** [comment]
On Mon, Jun 29, 2015 at 3:57 AM, jwaterloo <notifications@github.com> wrote:

> what do windows user do about qemu
>
Install Linux? :)
Seriously, on Windows you can use Capstan to run and download
images but not to build them
